### ISSUE TITLE
Capabilities

### ISSUE THREAD

**Issue by hasanalizxc** [shelru/ExtraMirror#18]
Dear shelru,

Hope you are fine. I examined this project and couldn't understand completely. What do you mean protection and what can we do with extra mirror? Can you tell us all of them (capabilities)? And another question is what is Minibase?

Thank you so much.

**Comment by shelru** [comment]
>what is Minibase?
Dir.
>what can we do with extra mirror?
protect Counter-Strike client from server side slowhacks, like: block some cmds, inject some libraries, change players models, hide cmds, add cmds, block events, block amxx hud messages, block motd, change steamid to rand[RevEmu], hide files, hide real cvar values, fix demobuffer bug & e/t/c
